# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./orderbook.h
SOURCES += ./main.cpp \
    ./orderbook.cpp
FORMS += ./orderbook.ui
RESOURCES += orderbook.qrc
